### ISSUE TITLE
README and blog post mismatch

### ISSUE THREAD

**Issue by Thomson42** [cosmicjs/gatsby-blog-cosmicjs#1]
I just finished some debugging while I was trying to start using this gatsby code. As it turns out Your README documentation has the correct starting code snippet but the gatsby blog post about your gatsby-blog-cosmicjs starter has yet to be updated and currently misdirects users (as I discovered) to replace their gatsby-config.js file with the given code. The code in the blog is missing its siteMetadata and if directly replaced will result in an error. 

If at all possible please edit the gatsby blog post to better reflect your current documentation, thanks.

**Comment by jazibsawar** [comment]
Hi @Thomson42, in our https://github.com/jazibsawar/gatsby-blog-cosmicjs we are pulling all siteMetadata from Cosmic JS Object (Bucket). The removal of siteMetadata from gatsby-config.js is intentional. Please configure your bucket as per instructions in the blog. 
We missed one thing in Readme. I will update it.
